# CAVEAT - THIS FILE MUST BE USED FOR LOCAL DEVELOPMENT PURPOSE ONLY
# For full spec of docker-compose: @see https://docs.docker.com/compose/compose-file/

services:

  mysql:
    image: appkr/mysql:5.7-arm64
    container_name: mysql
    volumes:
      - $HOME/mysql_data:/var/lib/mysql/
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.conf
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - 3306:3306
    command: mysqld --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
    healthcheck:
      test: mysql -e 'SELECT 1' 2>/dev/null || mysql -uroot -psecret -e 'SELECT 1' 2>/dev/null || exit 1

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    platform: linux/amd64
    container_name: zookeeper
    ports:
      - 2181:2181
    healthcheck:
      test: nc -z localhost 2181 || exit 1

  kafka:
    image: niks123123/kafka:latest
    container_name: kafka
    environment:
      KAFKA_CREATE_TOPICS: "local-example-output:1:1"
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    ports:
      - 9092:9092
    healthcheck:
      test: nc -z localhost 9092 || exit 1

  jhipster-uaa:
    image: appkr/jhipster-uaa:arm64
    container_name: jhipster-uaa
    ports:
      - 9999:9999
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: curl -s http://localhost:9999/management/health || exit 1
      start_period: 90s
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/jhipster_uaa?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=secret
